name: wa_example
description: Storybook app exercising the wa widget library.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.0-8.0.dev <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter
  wa:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
